### ISSUE TITLE
SSID "Generic ESP8266 Firmware" not showing

### ISSUE THREAD

**Issue by emilnorde** [maakbaas/esp8266-iot-framework#57] opened 2020-11-21 12:42 UTC
Hi!

I followed your instructions steps 1-10 with "timeSyncExample.cpp" as example code. Uploading code to esp8266 works great and without any issues. 

On step 11 though, no WiFi with SSID of Generic ESP8266 Firmware is detected. 

Serial monitor show:

> Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000

over and over again. 

What am I doing wrong?

Best regards.

**Comment by maakbaas** [comment] 2020-11-21 13:31
I don't know ;).

What is your hardware version, what is the PlatformIO version, and what is the version of the framework? And can you share the complete terminal output when you build for and flash the esp8266?

I can not reproduce this in any way. So more details would be needed to help your case.

**Comment by maakbaas** [comment] 2020-11-21 13:32
As a side note: the docs should be updated, the actual firmware name you should be looking for is 

`ESP8266 IoT Framework`. 

But it sounds like this is not the issue here.

**Comment by emilnorde** [comment] 2020-11-21 14:20
Haha, yes. :) First of all, thanks for quick response. 

I use the VS Code extension and installed the esp8266-iot-framework via PlatformIO Library Manager 
I added `lib_deps = ESP8266 IoT Framework` to the platformio.ini file as instructed. 

Also executed the command `pip install asn1crypto` after getting error message of that missing (followed the issue in #51 )

When I build and upload this is what the terminal shows:
```
> Executing task in folder esp8266_test3: C:\Users\emiln\.platformio\penv\Scripts\pio.exe run --target upload <

Processing esp01_1m (platform: espressif8266; board: esp01_1m; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 (2.6.2) > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - tool-mklittlefs 1.203.200522 (2.3)
 - tool-mkspiffs 1.200.0 (2.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 34 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266 IoT Framework> 1.6.1
|   |-- <ESP Async WebServer> 1.2.3
|   |   |-- <ESPAsyncTCP> 1.2.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson> 6.17.2
|   |-- <ArduinoJson> 6.17.2
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <DNSServer> 1.1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <EEPROM> 1.0
|   |-- <LittleFS(esp8266)> 0.1.0
|-- <LittleFS(esp8266)> 0.1.0
Building in release mode
Retrieving maximum program size .pio\build\esp01_1m\firmware.elf
Checking size .pio\build\esp01_1m\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  45.2% (used 37004 bytes from 81920 bytes)
Flash: [========  ]  77.4% (used 589688 bytes from 761840 bytes)
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM8
Uploading .pio\build\esp01_1m\firmware.bin
esptool.py v2.8
Serial port COM8
Connecting........_____
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 48:3f:da:70:b3:64
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 593840 bytes to 440846...

Writing at 0x00000000... (3 %)
Writing at 0x00004000... (7 %)
Writing at 0x00008000... (11 %)
Writing at 0x0000c000... (14 %)
Writing at 0x00010000... (18 %)
Writing at 0x00014000... (22 %)
Writing at 0x00018000... (25 %)
Writing at 0x0001c000... (29 %)
Writing at 0x00020000... (33 %)
Writing at 0x00024000... (37 %)
Writing at 0x00028000... (40 %)
Writing at 0x0002c000... (44 %)
Writing at 0x00030000... (48 %)
Writing at 0x00034000... (51 %)
Writing at 0x00038000... (55 %)
Writing at 0x0003c000... (59 %)
Writing at 0x00040000... (62 %)
Writing at 0x00044000... (66 %)
Writing at 0x00048000... (70 %)
Writing at 0x0004c000... (74 %)
Writing at 0x00050000... (77 %)
Writing at 0x00054000... (81 %)
Writing at 0x00058000... (85 %)
Writing at 0x0005c000... (88 %)
Writing at 0x00060000... (92 %)
Writing at 0x00064000... (96 %)
Writing at 0x00068000... (100 %)
Wrote 593840 bytes (440846 compressed) at 0x00000000 in 38.8 seconds (effective 122.5 kbit/s)...
Hash of data verified.

Leaving...
Soft resetting...
================================================================== [SUCCESS] Took 46.45 seconds ==================================================================

Terminal will be reused by tasks, press any key to close it.
```

And then, no WiFi sent from esp8266 to connect to :(

**Comment by maakbaas** [comment] 2020-11-21 16:01
Thats interesting.

- What is the exact hardware/development board you are using?
- Can you delete your .pio folder and build/flash again, and paste that log?
- Do you have a second board to try by any chance? 
- Have you tried one of the other example C files to see if that changes anything?

**Comment by emilnorde** [comment] 2020-11-21 16:50
I went back to the basics as I never used platformIO as IDE for esp8266. Tried to upload simple Blink program through it. 


```
/*
 * Blink
 * Turns on an LED on for one second,
 * then off for one second, repeatedly.
 */

#include "Arduino.h"

void setup()
{
  Serial.begin(115200);
  // initialize LED digital pin as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop()
{
  // turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_BUILTIN, HIGH);
  // wait for a second
  delay(1000);
  // turn the LED off by making the voltage LOW
  digitalWrite(LED_BUILTIN, LOW);
   // wait for a second
  delay(1000);
}
```
It uploads but the esp8266 doesn't blink.

Tried with the same code but uploading through Arduino IDE, and it works. So perhaps some wrong setting in PlatformIO? Can´t figure it out.

Hardware: 
----
ESP8266-01 connected through an Arduino UNO via RX/TX pins. (Uploaded programs without issues through Arduino IDE as described. )

https://www.amazon.com/HiLetgo-Wireless-Transceiver-Development-Compatible/dp/B010N1ROQS/ref=sr_1_9?dchild=1&keywords=esp-01&qid=1605975828&sr=8-9


Terminal after removing .pio
-----
```
> Executing task in folder esp8266_test3: C:\Users\emiln\.platformio\penv\Scripts\pio.exe run --target upload <

Processing esp01_1m (platform: espressif8266; board: esp01_1m; framework: arduino)
---------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 (2.6.2) > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - tool-mklittlefs 1.203.200522 (2.3) 
 - tool-mkspiffs 1.200.0 (2.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing ESP8266 IoT Framework
Library Manager: ESP8266 IoT Framework @ 1.6.1 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing ESP Async WebServer
Library Manager: ESP Async WebServer @ 1.2.3 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing ESPAsyncTCP
Library Manager: ESPAsyncTCP @ 1.2.2 has been installed!
Library Manager: Installing AsyncTCP
Library Manager: AsyncTCP @ 1.1.1 has been installed!
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Library Manager: Installing ArduinoJson
Library Manager: ArduinoJson @ 6.17.2 has been installed!
Library Manager: Installing ESP8266WiFi
Library Manager: Already installed, built-in library
Library Manager: Installing ESP8266HTTPClient
Library Manager: Already installed, built-in library
Library Manager: Installing DNSServer
Library Manager: DNSServer @ 1.1.0 has been installed!
Library Manager: Installing EEPROM
Library Manager: Warning! More than one package has been found by EEPROM requirements:
 - mbed-floatlei/eeprom @ 0.0.0+sha.b71fbcf5b8e4
 - mbed-yasuyuki/EEPROM @ 0.0.0-alpha+sha.25e5bc71e6
 - mbed-bborredon/eeprom @ 0.0.0+sha.925096a4c7f0
 - mbed-olympux/eeprom @ 0.0.0+sha.34cb334d111b
 - mbed-jackb/EEPROM @ 0.0.0+sha.b90c5754d8db
 - skydome/eeprom @ 0.0.7
 - mbed-okini3939/eeprom @ 0.0.0+sha.724b44e46ecf
 - mbed-wodji/EEPROM @ 0.0.0-alpha+sha.3be39cc460
 - mbed-fra221-2015/eeprom @ 0.0.0+sha.df82ebf4be54
 - mbed-chaithanyarss/eeprom @ 0.0.0+sha.b65b74065b7f
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Library Manager: eeprom @ 0.0.0+sha.b71fbcf5b8e4 has been installed!
Library Manager: Installing LittleFS(esp8266)
Library Manager: Already installed, built-in library
Found 34 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266 IoT Framework> 1.6.1
|   |-- <ESP Async WebServer> 1.2.3
|   |   |-- <ESPAsyncTCP> 1.2.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson> 6.17.2
|   |-- <ArduinoJson> 6.17.2
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <DNSServer> 1.1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <EEPROM> 1.0
|   |-- <LittleFS(esp8266)> 0.1.0
|-- <LittleFS(esp8266)> 0.1.0
Building in release mode
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\WiFiManager.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\certStore.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\configManager.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\dashboard.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\fetch.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\generated\config.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\timeSync.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\updater.cpp.o
Compiling .pio\build\esp01_1m\lib07e\ESP8266 IoT Framework\webServer.cpp.o
Compiling .pio\build\esp01_1m\src\main.cpp.o
Generating LD script .pio\build\esp01_1m\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiServerSecureAxTLS.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\esp01_1m\lib2af\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\esp01_1m\lib50e\ESPAsyncTCP\AsyncPrinter.cpp.o
Compiling .pio\build\esp01_1m\lib50e\ESPAsyncTCP\ESPAsyncTCP.cpp.o
Compiling .pio\build\esp01_1m\lib50e\ESPAsyncTCP\ESPAsyncTCPbuffer.cpp.o
Compiling .pio\build\esp01_1m\lib50e\ESPAsyncTCP\SyncClient.cpp.o
Compiling .pio\build\esp01_1m\lib50e\ESPAsyncTCP\tcp_axtls.c.o
Compiling .pio\build\esp01_1m\libe96\Hash\Hash.cpp.o
Archiving .pio\build\esp01_1m\libbe6\libArduinoJson.a
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\SPIFFSEditor.cpp.o
Archiving .pio\build\esp01_1m\lib2af\libESP8266WiFi.a
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\WebAuthentication.cpp.o
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\WebHandlers.cpp.o
Archiving .pio\build\esp01_1m\libe96\libHash.a
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\WebRequest.cpp.o
Archiving .pio\build\esp01_1m\lib50e\libESPAsyncTCP.a
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\esp01_1m\libbc4\ESP Async WebServer\WebServer.cpp.o
In file included from .pio\libdeps\esp01_1m\ESP Async WebServer\src\SPIFFSEditor.cpp:1:0:
.pio\libdeps\esp01_1m\ESP Async WebServer\src\SPIFFSEditor.h:16:101: 
warning: 'SPIFFS' is deprecated (declared at C:\Users\emiln\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/FS.h:269): SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
     SPIFFSEditor(const String& username=String(), const String& password=String(), const fs::FS& fs=SPIFFS);

                                ^
Compiling .pio\build\esp01_1m\libbdc\ESP8266HTTPClient\ESP8266HTTPClient.cpp.o
Compiling .pio\build\esp01_1m\lib3a0\DNSServer\DNSServer.cpp.o
Compiling .pio\build\esp01_1m\lib8cb\EEPROM\EEPROM.cpp.o
Compiling .pio\build\esp01_1m\lib51e\LittleFS\LittleFS.cpp.o
Compiling .pio\build\esp01_1m\lib51e\LittleFS\lfs.c.o
Archiving .pio\build\esp01_1m\lib3a0\libDNSServer.a
Archiving .pio\build\esp01_1m\lib8cb\libEEPROM.a
Compiling .pio\build\esp01_1m\lib51e\LittleFS\lfs_util.c.o
Archiving .pio\build\esp01_1m\libFrameworkArduinoVariant.a
Archiving .pio\build\esp01_1m\libbdc\libESP8266HTTPClient.a
Compiling .pio\build\esp01_1m\FrameworkArduino\Crypto.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Esp-frag.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Esp-version.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\FS.cpp.o
Archiving .pio\build\esp01_1m\libbc4\libESP Async WebServer.a
Compiling .pio\build\esp01_1m\FrameworkArduino\FSnoop.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Print.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Schedule.cpp.o
Archiving .pio\build\esp01_1m\lib51e\libLittleFS.a
Compiling .pio\build\esp01_1m\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\StreamString.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\TypeConversion.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\Updater.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\WString.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\abi.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\base64.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\cont.S.o
Compiling .pio\build\esp01_1m\FrameworkArduino\cont_util.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_eboot_command.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_features.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_flash_quirks.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_flash_utils.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_i2s.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_main.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_noniso.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_phy.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_postmortem.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_si2c.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_sigma_delta.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_spi_utils.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_timer.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_waveform.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring_analog.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring_digital.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring_pulse.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring_pwm.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\core_esp8266_wiring_shift.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\crc32.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\debug.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\flash_hal.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\gdb_hooks.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\heap.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\libc_replacements.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\sntp-lwip2.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs\spiffs_cache.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs\spiffs_check.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs\spiffs_gc.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs\spiffs_hydrogen.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs\spiffs_nucleus.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\spiffs_api.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\sqrt32.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\time.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\uart.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\umm_malloc\umm_info.c.o
Compiling .pio\build\esp01_1m\FrameworkArduino\umm_malloc\umm_integrity.c.o
Compiling .pio\build\esp01_1m\FrameworkArduino\umm_malloc\umm_local.c.o
Compiling .pio\build\esp01_1m\FrameworkArduino\umm_malloc\umm_malloc.cpp.o
Compiling .pio\build\esp01_1m\FrameworkArduino\umm_malloc\umm_poison.c.o
Archiving .pio\build\esp01_1m\libFrameworkArduino.a
Linking .pio\build\esp01_1m\firmware.elf
Building .pio\build\esp01_1m\firmware.bin
Retrieving maximum program size .pio\build\esp01_1m\firmware.elf
Checking size .pio\build\esp01_1m\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  45.2% (used 37004 bytes from 81920 bytes)
Flash: [========  ]  77.4% (used 589688 bytes from 761840 bytes)     
Creating BIN file ".pio\build\esp01_1m\firmware.bin" using "C:\Users\emiln\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" and ".pio\build\esp01_1m\firmware.elf"
Configuring upload protocol...
AVAILABLE: espota, esptool
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM8
Uploading .pio\build\esp01_1m\firmware.bin
esptool.py v2.8
Serial port COM8
Connecting........_____....._____.
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 48:3f:da:70:b3:64
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 593840 bytes to 440846...

Writing at 0x00000000... (3 %)
Writing at 0x00004000... (7 %)
Writing at 0x00008000... (11 %)
Writing at 0x0000c000... (14 %)
Writing at 0x00010000... (18 %)
Writing at 0x00014000... (22 %)
Writing at 0x00018000... (25 %)
Writing at 0x0001c000... (29 %)
Writing at 0x00020000... (33 %)
Writing at 0x00024000... (37 %)
Writing at 0x00028000... (40 %)
Writing at 0x0002c000... (44 %)
Writing at 0x00030000... (48 %)
Writing at 0x00034000... (51 %)
Writing at 0x00038000... (55 %)
Writing at 0x0003c000... (59 %)
Writing at 0x00040000... (62 %)
Writing at 0x00044000... (66 %)
Writing at 0x00048000... (70 %)
Writing at 0x0004c000... (74 %)
Writing at 0x00050000... (77 %)
Writing at 0x00054000... (81 %)
Writing at 0x00058000... (85 %)
Writing at 0x0005c000... (88 %)
Writing at 0x00060000... (92 %)
Writing at 0x00064000... (96 %)
Writing at 0x00068000... (100 %)
Wrote 593840 bytes (440846 compressed) at 0x00000000 in 38.2 seconds 
(effective 124.4 kbit/s)...
Hash of data verified.

Leaving...
Soft resetting...
=================== [SUCCESS] Took 73.93 seconds ===================

Terminal will be reused by tasks, press any key to close it.
```
Other board
--------
I'm afraid i only have this one board available, but I've been able to connect to websites with it before. So it should work. 

Other example programs
---------
I've tried with `helloWorld.cpp` , `timeSyncExample.cpp` and `Minimal main.c`. 
No difference, still no WiFi to connect to.

**Comment by maakbaas** [comment] 2020-11-21 17:11
I will close this issue for now, since it is more of a generic setup/PlatformIO issue.

I found this thread, which might help you:
https://community.platformio.org/t/problem-upload-code-to-esp-01s/8411

you can try setting `board_build.flash_mode = dout` in your `platformio.ini`? Also you can try setting a lower `upload_speed` in that file, but other than that I have no immediate suggestions.

Good luck, and let me know if you manage to find the issue!

**Closed as completed by maakbaas** 2020-11-21 17:11 UTC

**Comment by alanjohnson** [comment] 2021-03-16 22:20
I wanted to also mention, that IF YOU had already used the Tzapu WifiManager, with the same board.  This will use the same credentials. So, you need to make sure to clear it (can use the included WiFiManager.forget()).  otherwise you will never see the SSID appear, as the board is actually already connected to your network from the previous settings.
